#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mlocate
Version  : 0.26
Release  : 3
URL      : https://src.fedoraproject.org/repo/pkgs/rpms/mlocate/mlocate-0.26.tar.xz/539e6f86bf387358aa2b14d5f880e49a/mlocate-0.26.tar.xz
Source0  : https://src.fedoraproject.org/repo/pkgs/rpms/mlocate/mlocate-0.26.tar.xz/539e6f86bf387358aa2b14d5f880e49a/mlocate-0.26.tar.xz
Source1  : mlocate-updatedb.service
Source2  : mlocate-updatedb.timer
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: mlocate-autostart = %{version}-%{release}
Requires: mlocate-bin = %{version}-%{release}
Requires: mlocate-data = %{version}-%{release}
Requires: mlocate-license = %{version}-%{release}
Requires: mlocate-locales = %{version}-%{release}
Requires: mlocate-man = %{version}-%{release}
Requires: mlocate-services = %{version}-%{release}
Patch1: 0001-Add-a-default-updatedb.conf-file.patch
Patch2: 0002-Stateless-make-updatedb-find-the-configuration-file-.patch
Patch3: 0003-Make-updatedb-create-the-DB-dir.patch
Patch4: 0004-Make-locate-suggest-running-updatedb-if-the-DB-isn-t.patch

%description
About
=====
mlocate is a locate/updatedb implementation.  The 'm' stands for "merging":
updatedb reuses the existing database to avoid rereading most of the file
system, which makes updatedb faster and does not trash the system caches as
much.

%package autostart
Summary: autostart components for the mlocate package.
Group: Default

%description autostart
autostart components for the mlocate package.


%package bin
Summary: bin components for the mlocate package.
Group: Binaries
Requires: mlocate-data = %{version}-%{release}
Requires: mlocate-license = %{version}-%{release}
Requires: mlocate-services = %{version}-%{release}

%description bin
bin components for the mlocate package.


%package data
Summary: data components for the mlocate package.
Group: Data

%description data
data components for the mlocate package.


%package license
Summary: license components for the mlocate package.
Group: Default

%description license
license components for the mlocate package.


%package locales
Summary: locales components for the mlocate package.
Group: Default

%description locales
locales components for the mlocate package.


%package man
Summary: man components for the mlocate package.
Group: Default

%description man
man components for the mlocate package.


%package services
Summary: services components for the mlocate package.
Group: Systemd services

%description services
services components for the mlocate package.


%prep
%setup -q -n mlocate-0.26
cd %{_builddir}/mlocate-0.26
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1

%build
## build_prepend content
sed -i '/^groupname /s/mlocate/locate/' Makefile.am
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604359706
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static --localstatedir=/var/lib
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604359706
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mlocate
cp %{_builddir}/mlocate-0.26/COPYING %{buildroot}/usr/share/package-licenses/mlocate/4cc77b90af91e615a64ae04893fdffa7939db84c
%make_install
%find_lang mlocate
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/mlocate-updatedb.service
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/systemd/system/mlocate-updatedb.timer
## install_append content
install -d %{buildroot}/usr/share/defaults/etc
install -m644 -t %{buildroot}/usr/share/defaults/etc updatedb.conf

mkdir -p %{buildroot}/usr/lib/systemd/system/timers.target.wants
ln -s ../mlocate-updatedb.timer %{buildroot}/usr/lib/systemd/system/timers.target.wants
## install_append end

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/timers.target.wants/mlocate-updatedb.timer

%files bin
%defattr(-,root,root,-)
%attr(2711,root,locate) /usr/bin/locate
/usr/bin/updatedb

%files data
%defattr(-,root,root,-)
/usr/share/defaults/etc/updatedb.conf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mlocate/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/locate.1
/usr/share/man/man5/mlocate.db.5
/usr/share/man/man5/updatedb.conf.5
/usr/share/man/man8/updatedb.8

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/timers.target.wants/mlocate-updatedb.timer
/usr/lib/systemd/system/mlocate-updatedb.service
/usr/lib/systemd/system/mlocate-updatedb.timer

%files locales -f mlocate.lang
%defattr(-,root,root,-)

